<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Servicio;
use App\Models\Departamento;

class SeederServicios extends Seeder
{
    public function run(): void
    {
        // ── Departamentos ──────────────────────────────────────
        $nombresDepartamentos = [
            'Departamento de Constructora',
            'Departamento Legal',
            'Departamento de Contabilidad',
            'Departamento de Mediación',
            'Departamento de Consultoría',
        ];

        foreach ($nombresDepartamentos as $nombre) {
            Departamento::firstOrCreate(['nombre_departamento' => $nombre]);
        }

        $this->command->info('✓ Departamentos verificados/creados');

        // ── Servicios ──────────────────────────────────────────
        $deptos = Departamento::pluck('id', 'nombre_departamento');

        $servicios = [

            // ══════════════════════════════════════════════════
            // CONSTRUCTORA
            // ══════════════════════════════════════════════════
            'Departamento de Constructora' => [
                'Permiso de construcción',
                'Permiso de cerramiento',
                'Permiso de derrocamiento',
                'Planimetría urbana',
                'Planimetría rural',
                'Replanteo topográfico',
                'Diseño arquitectónico',
                'Anteproyecto arquitectónico',
                'Planos estructurales, eléctricos, hidrosanitarios',
                'Construcción de cerramientos',
                'Derrocamientos',
                'Construcción de viviendas',
                'Construcción de locales',
                'Aceras y bordillos',
                'Portones y accesos',
                'Remodelaciones',
                'Ampliaciones',
                'Reforzamiento estructural',
                'Mantenimiento de viviendas',
                'Pintura y acabados',
                'Dirección técnica',
                'Fiscalización de obra',
                'Informes técnicos',
                'Subdivisión urbana',
                'Subdivisión rural',
                'Lotización urbana',
                'Lotización rural',
                'Diseño vial interno',
                'Diseño de áreas verdes',
                'Diseño de redes de agua',
                'Diseño de alcantarillado',
                'Diseño eléctrico de lotización',
                'Ejecución de obras de lotización',
                'Asesoría técnica integral',
                'Estudios de suelo',
                'Actualización de planos por ampliaciones',
                'Presupuesto de obra',
                'Cronograma de obra',
                'Estudios de factibilidad constructiva',
                'Certificados de línea de fábrica',
                'Propiedad horizontal',
                'Regularización de construcciones no declaradas',
                'Avalúos técnicos comerciales',
                'Informes técnicos para juicios o conflictos',
                'Declaratoria de construcción',
                'Actualización catastral',
            ],

            // ══════════════════════════════════════════════════
            // CONTABILIDAD
            // ══════════════════════════════════════════════════
            'Departamento de Contabilidad' => [
                'Declaración renta',
                'Cierre fiscal',
                'Anexo ATS',
                'Declaración IVA',
                'Contabilidad completa',
                'Flujo de caja',
                'Conciliación bancaria',
                'Control financiero',
                'Registro contable',
                'Control inventarios',
                'Estados financieros',
                'Rentabilidad',
                'Indicadores',
                'Análisis gastos',
                'Roles de pago',
                'CFO externo',
                'Acompañamiento empresarial',
                'Organización',
                'Control interno',
                'Auditoría interna',
                'Auditoría',
                'Reestructuración',
                'Costeo',
                'Presupuesto',
                'Contratos',
                'Liquidaciones',
                'Planeación fiscal',
                'Reestructuración empresa',
                'Atrasos contables',
                'Fiscalización',
                'Deudas',
                'Regularización total',
                'Planificación tributaria',
                'Devolución impuestos',
                'Revisión tributaria',
                'Declaraciones atrasadas',
                'Multas',
                'Suspensión RUC',
                'Actualización RUC',
                'Apertura RUC en Servicio de Rentas Internas',
                'Inicio actividades',
                'Régimen RIMPE',
                'Facturación electrónica',
                'Implementación contable',
                'Inventario inicial',
                'Registro de activos',
                'Balance inicial',
                'Apertura contable',
                'Afiliación IESS',
            ],

            // ══════════════════════════════════════════════════
            // LEGAL
            // ══════════════════════════════════════════════════
            'Departamento Legal' => [
                'Niegan la información pública para gestionar tus trámites',
                'Privación de la libertad arbitraria',
                'Despidos arbitrarios en el sector público',
                'Sanciones administrativas laborales sin un proceso justo',
                'Multas o sanciones sin un proceso justo',
                'Poder General',
                'Poder Especial',
                'Declaración Juramentada',
                'Contrato prestación de servicios',
                'Contrato compra-venta propiedades (promesa)',
                'Contrato compra-venta negocios',
                'Contrato de arrendamiento',
                'Contrato de trabajo',
                'Estafa',
                'Traspaso dominio por donación',
                'Traspaso dominio por compra-venta',
                'Escritura de tierras por Adjudicación (Subsecretaría de Tierras)',
                'Aclaratoria de escritura',
                'Adjudicación MIDUVI',
                'Cobro de pagaré',
                'Cobro de letra de cambio',
                'Cobro de cheques',
                'Ejecución de actas de mediación',
                'Divorcio por petición de uno de los cónyuges cuando no exista acuerdo voluntario',
                'Divorcio mutuo acuerdo sin hijos',
                'Divorcio mutuo acuerdo con hijos',
                'Legalización de Uniones de Hecho',
                'Autorización de Segundas Nupcias para contraer matrimonio',
                'Permiso y cancelación de patente',
                'Prescripción adquisitiva de dominio',
                'Nulidad de contrato',
                'Incumplimiento de Contrato',
                'Nulidad de testamento',
                'Rebaja de la pena privativa no menor a 10 años',
                'Suspensión condicional de la pena mayor o igual a 5 años para personas adultas mayores o con enfermedades catastróficas',
                'Juicio por Lesiones graves en accidente de tránsito',
                'Pensiones alimenticias',
                'Rebaja y aumento de pensiones alimenticias',
                'Régimen de visitas de hijos y tenencia',
                'Privación de Patria Potestad',
                'Boletas de auxilio',
                'Boletas de apremio por falta de pago',
                'Autorización de venta de bienes inmuebles de menores de edad',
                'Tenencia de menores de edad',
                'Autorización de salida del país del menor por negativa de uno de los padres',
                'Posesión efectiva (un heredero)',
                'Posesión efectiva (varias propiedades)',
                'Testamento abierto',
                'Testamento cerrado',
                'Accidente de tránsito con daños materiales',
                'Registro de marca',
                'Constitución de S.A.S. (Sociedad por Acciones Simplificada)',
                'Asesoría en propiedad intelectual',
            ],

            // ══════════════════════════════════════════════════
            // MEDIACIÓN
            // ══════════════════════════════════════════════════
            'Departamento de Mediación' => [
                'Pagos pendientes',
                'Beneficios laborales',
                'Conflictos internos laborales',
                'Acoso laboral',
                'Compra-venta de bienes',
                'Herencias y sucesiones familiares',
                'Herencias en vida',
                'Disputas de donaciones familiares',
                'Reestructuración de patrimonios familiares',
                'Reparto de bienes muebles familiares',
                'Conflictos por patrimonio intangible',
                'Compra-venta de terrenos',
                'Herencias de propiedades',
                'Propiedad horizontal',
                'Subdivisiones de terrenos',
                'Posesión de terrenos',
                'Conflictos de venta de propiedades',
                'Promesas de compra incumplidas',
                'División de terrenos',
                'Mediación para deudor individual',
                'Conflictos con tarjetas de crédito',
                'Conflictos con préstamos personales',
                'Reestructuración de deudas',
                'Mediación de deudas bancarias',
                'Revisión de intereses excesivos',
                'Conflictos de microcréditos',
                'Conflictos de crédito productivo',
                'Negociación de pagos parciales',
                'Deudas por servicios impagos',
                'Conflictos de cartera empresarial',
                'Garantías y avales impugnados',
                'Acuerdos de inversión',
                'Conflictos de cooperativas',
                'Cobros indebidos',
                'Problemas de cobro en arrendamientos',
                'Ajustes de saldo pendiente',
                'Reclamos por publicidad engañosa',
                'Conflictos de arrendamiento comercial',
                'Intérprete de términos de servicio',
                'Modificación de términos contractuales',
                'Mediación en divorcios y separación',
                'Pensión alimenticia',
                'Custodia de hijos',
                'Régimen de visitas',
                'Acuerdos de crianza',
                'Conflictos padres e hijos',
                'Reparto de bienes tras separación',
                'Mediación entre hermanos',
                'Acuerdos prenupciales',
                'Conflictos de hogar y convivencia',
                'Administración de bienes familiares',
                'Mediación de tutela',
                'Acuerdos de cuidado familiar',
                'Conflictos con abuelos',
                'Custodia compartida',
                'Uso de bienes familiares',
                'Problemas de comunicación familiar',
                'Acuerdos familiares avanzados',
                'Solución integral de conflictos domésticos',
                'Mediación para padres primerizos',
                'Decisiones sobre educación de hijos',
                'Coordinación de visitas múltiple',
                'Conflictos intergeneracionales familiares',
                'Divorcio por mutuo acuerdo internacional',
                'Acuerdos educativos familiares',
                'Conflictos de tutores legales',
                'Problemas de lindero y límites',
                'Conflictos por arriendos',
                'Servidumbres y paso',
                'Paso de acceso',
                'Uso de suelo',
                'Despidos',
                'Acuerdos de salida voluntaria',
                'Diferencias salariales',
                'Vacaciones no otorgadas',
                'Conflictos vecinales',
                'Convivencia urbana',
                'Áreas comunes',
                'Ruidos',
                'Conflictos comunitarios',
                'Organización de juntas vecinales',
                'Regulaciones internas de comunidad',
                'Seguridad vecinal',
                'Uso de instalaciones comunes',
                'Conflictos de espacios públicos',
                'Conflictos entre estudiantes',
                'Conflictos padres-docentes',
                'Conflictos en universidades',
                'Problemas en colegios',
                'Conflictos institucionales',
                'Conflictos gremiales',
                'Conflictos cooperativos',
                'Conflictos deportivos',
                'Mediación cultural',
                'Proyectos educativos',
                'Acuerdos de pago extrajudicial',
                'Conflictos con financieras',
                'Deudas comerciales',
                'Deudas entre empresas',
                'Incumplimiento de pago comercial',
                'Deudas hipotecarias',
                'Deudas vehiculares',
                'Conflictos por facturas impagas',
                'Reclamaciones de cheque rechazado',
                'Mediación de pagos de servicios públicos',
                'Disputas con entidades financieras',
                'Acuerdos de financiamiento empresarial',
                'Negociación de intereses por mora',
                'Contratos incumplidos',
                'Disputas societarias',
                'Conflictos con proveedores',
                'Acuerdos comerciales',
                'Daños y perjuicios civiles',
                'Negociación de distribución de utilidades',
                'Conflictos de ventas',
                'Garantías de productos defectuosos',
                'Servicios técnicos incumplidos',
                'Conflictos por contratos digitales',
                'Responsabilidad civil',
                'Incumplimiento de entregas',
                'Atención a reclamaciones comerciales',
                'Contratos de obra',
                'Servicios profesionales insuficientes',
                'Negociación de alianzas estratégicas',
                'Disputas por licencias comerciales',
                'Distribución de dividendos',
                'Disputas de contratos de logística',
                'Conflictos de importación y exportación',
                'Negociación de acuerdos de franquicia',
                'Contratos de marketing digital',
                'Outsourcing y subcontratos',
                'Conflictos de transporte comercial',
                'Acuerdos de representación comercial',
                'Intereses de negocio familiar',
                'Distribución de activos empresariales',
                'Reajuste de precios negociados',
                'Arbitraje preventivo de contratos',
                'Resolución de disputas internas',
                'Conflictos entre departamentos',
                'Problemas con proveedores externos',
                'Servicios interempresariales no entregados',
                'Resolución de disputas de pagos terceros',
                'Revisiones de cláusulas de contratos',
                'Pensiones atrasadas',
                'Conflictos económicos familiares',
                'Conflictos post-separación',
                'Acuerdos sucesorios complejos',
                'Disputas de vivienda familiar',
                'Revisión de manutenciones',
                'Conflictos de testamentos',
                'Custodia internacional',
                'Bienes en proindiviso',
                'Construcción de inmuebles',
                'Entrega de inmuebles',
                'Uso de propiedad vecinal',
                'Ocupación indebida de terrenos',
                'Regularización de propiedad',
                'Avalúos y tasaciones conflictivas',
                'Problemas de escrituras',
                'Conflictos de urbanización',
                'Lotes rurales',
                'Lotes urbanos',
                'Conflictos por cerramientos',
                'Construcción ilegal',
                'Remodelaciones conflictivas',
                'Conflictos de obra',
                'Invasiones de terreno',
                'Regularización de tierras comunitarias',
                'Contratos laborales',
                'Renuncias conflictivas',
                'Horas extras impagas',
                'Bonos pendientes',
                'Sanciones laborales',
                'Teletrabajo',
                'Conflictos con sindicatos',
                'Reclamos laborales generales',
                'Seguridad laboral',
                'Reincorporaciones laborales',
                'Evaluaciones y promociones conflictivas',
                'Accidentes de tránsito',
                'Daños materiales',
                'Conflictos entre conductores',
                'Reclamaciones aseguradoras de tránsito',
                'Transporte público',
                'Transporte de mercancías',
                'Conflictos de carga y logística',
                'Accidentes laborales en transporte',
                'Reclamaciones a transporte privado',
                'Multas y sanciones',
                'Conflictos con clínicas',
                'Conflictos con médicos',
                'Conflictos con seguros médicos',
                'Reclamaciones de seguros',
                'Acuerdos de compensación sanitaria',
                'Conflictos de software',
                'Conflictos en redes sociales',
                'Propiedad intelectual digital',
                'Conflictos tecnológicos generales',
                'Elaboración de acta de mediación',
            ],

            // ══════════════════════════════════════════════════
            // CONSULTORÍA
            // ══════════════════════════════════════════════════
            'Departamento de Consultoría' => [
                'Diagnóstico organizacional',
                'Niveles jerárquicos',
                'Diseño de organigrama',
                'Elaboración del manual de funciones',
                'Alineación con normativa laboral y buenas prácticas administrativas',
                'Socialización y capacitación (10 horas)',
                'Socialización y capacitación (30 horas)',
                'Informe y entrega final de productos',
                'Diagnóstico Norma ISO 15489',
                'Construcción de cuadro general de clasificación documental',
                'Construcción de tabla de permanencia de plazos',
                'Política de gestión documental y archivo',
                'Manual de gestión documental y archivo',
                'Diagnóstico y evaluación de cumplimiento',
                'Diseño de políticas y protocolos adaptados a la realidad de cada socio local',
                'Desarrollo de plan de implementación con cronograma, recursos y recomendaciones',
                'Capacitación (30 horas)',
                'Seguimiento e implementación de procesos',
                'Diagnóstico participativo de brechas de violencia',
                'Diseño de política parroquial para prevención',
                'Programas de empoderamiento económico con enfoque de género',
                'Construcción de redes comunitarias de apoyo y producción',
                'Rutas de atención',
                'Comunicación comunitaria',
                'Monitoreo, evaluación e impacto social',
            ],
        ];

        foreach ($servicios as $deptoNombre => $lista) {
            $deptoId = $deptos[$deptoNombre] ?? null;

            if (!$deptoId) {
                $this->command->warn("Departamento no encontrado: {$deptoNombre}");
                continue;
            }

            foreach (array_unique($lista) as $nombre) {
                Servicio::firstOrCreate(
                    ['nombre_servicio' => $nombre, 'departamento_id' => $deptoId],
                    ['precio_sugerido' => 0, 'estatus' => 'Activo']
                );
            }

            $this->command->info("✓ {$deptoNombre}: " . count(array_unique($lista)) . ' servicios');
        }
    }
}
